### ISSUE TITLE
exit won't work after entering invalid command

### ISSUE THREAD

**Issue by rootonchair** [rootonchair/os-hell#8]
Open shell and type random invalid command
E.g. `ll`
then type exit, it won't work unless you try again several times

**Comment by zamminhduy123** [comment]
this suppose to be your task when u wrote the execute command

**Comment by rootonchair** [comment]
I don't think it's relevant to command execution. However, I will debugging it tonight.
There are two things need to make clear:
* Issues are the problem the problem is encountering. Not an assignment board so anyone could raise issues when they detect something wrong in the program
* I don't really like blaming each other so these problems are ours tasks. Please tell me directly if something's wrong with my working attitude. I'm open for feedback

**Comment by zamminhduy123** [comment]
# Just to correct your grammar "will + V" *kd* 

# I just debuged and found that even the enum type got the value of 2 - which is EXIT - the loop still keep going. Haven't found the place where all of this got in trouble

**Comment by rootonchair** [comment]
What happen? Something's wrong? Just to confirm you're alright

**Comment by zamminhduy123** [comment]
i don't even know. Still trying to figure why the loop keep going even we call exit(). Maybe something wrong with the thread ?

It's hard to debug in VMware, i can only use printf. Is there a way to bug like vs?

**Comment by rootonchair** [comment]
OK, let me take care of this. You can use `gdb`, debugger for Linux

**Comment by zamminhduy123** [comment]
nah i fixed it. just lack of exit when execvp return error. but u will need to test more cuz i just test the cases i can think of
